# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(772, 537)
        self.label_bg = QtWidgets.QLabel(Form)
        self.label_bg.setGeometry(QtCore.QRect(60, 50, 610, 410))
        self.label_bg.setStyleSheet("QLabel{\n"
"background-color: rgb(19, 20, 50);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"border:0px solid #298DFF; /* 无边框 */\n"
"}")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.label_bg_2 = QtWidgets.QLabel(Form)
        self.label_bg_2.setGeometry(QtCore.QRect(209, 50, 501, 410))
        self.label_bg_2.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"border:0px solid #298DFF; /* 无边框 */\n"
"}")
        self.label_bg_2.setText("")
        self.label_bg_2.setObjectName("label_bg_2")
        self.label_Name = QtWidgets.QLabel(Form)
        self.label_Name.setGeometry(QtCore.QRect(86, 70, 101, 51))
        self.label_Name.setStyleSheet("QLabel{\n"
"color: rgb(251, 254, 255);\n"
"    font: 24pt \"华文细黑\";\n"
"font-weight:bold;\n"
"}")
        self.label_Name.setObjectName("label_Name")
        self.pushButton_register = QtWidgets.QPushButton(Form)
        self.pushButton_register.setGeometry(QtCore.QRect(66, 160, 143, 44))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setStyleSheet("QPushButton{\n"
"font: 11pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 8px;    \n"
"text-align : left;\n"
"padding-left: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"font-weight:bold;\n"
"border: 0px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"background-color: rgb(32, 34, 89);\n"
"border: 2px solid rgb(43, 50, 61);\n"
"font-weight:bold;\n"
"    \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/register1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_register.setIcon(icon)
        self.pushButton_register.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_register.setObjectName("pushButton_register")
        self.label_roll = QtWidgets.QLabel(Form)
        self.label_roll.setGeometry(QtCore.QRect(60, 160, 6, 44))
        self.label_roll.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:6px;\n"
"border-bottom-right-radius:6px;\n"
"}")
        self.label_roll.setText("")
        self.label_roll.setObjectName("label_roll")
        self.pushButton_recognition = QtWidgets.QPushButton(Form)
        self.pushButton_recognition.setGeometry(QtCore.QRect(66, 204, 143, 44))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_recognition.setFont(font)
        self.pushButton_recognition.setStyleSheet("QPushButton{\n"
"font: 11pt \"Times New Roman\";\n"
"    color: rgb(255, 255, 255);\n"
"border-radius: 8px;    \n"
"text-align : left;\n"
"padding-left: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"font-weight:bold;\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"background-color: rgb(32, 34, 89);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    font-weight:bold;\n"
"    \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/user-images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_recognition.setIcon(icon1)
        self.pushButton_recognition.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_recognition.setObjectName("pushButton_recognition")
        self.pushButton_verification = QtWidgets.QPushButton(Form)
        self.pushButton_verification.setGeometry(QtCore.QRect(66, 248, 143, 44))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_verification.setFont(font)
        self.pushButton_verification.setStyleSheet("QPushButton{\n"
"font: 11pt \"Times New Roman\";\n"
"    color: rgb(255, 255, 255);\n"
"border-radius: 8px;    \n"
"text-align : left;\n"
"padding-left: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"font-weight:bold;\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"background-color: rgb(32, 34, 89);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    font-weight:bold;\n"
"    \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_verification.setIcon(icon2)
        self.pushButton_verification.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_verification.setObjectName("pushButton_verification")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 350, 91, 91))
        self.label.setStyleSheet("image: url(:/resources/facial-recognition.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(240, 100, 441, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_reg_bg = QtWidgets.QLabel(self.page)
        self.label_reg_bg.setGeometry(QtCore.QRect(50, 90, 210, 170))
        self.label_reg_bg.setStyleSheet("QLabel{\n"
"background-color: rgb(233, 82, 63);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"}")
        self.label_reg_bg.setText("")
        self.label_reg_bg.setObjectName("label_reg_bg")
        self.label_reg_logo = QtWidgets.QLabel(self.page)
        self.label_reg_logo.setGeometry(QtCore.QRect(80, 110, 40, 40))
        self.label_reg_logo.setStyleSheet("QLabel{\n"
"background-color: rgb(254, 113, 106);\n"
"border-radius: 12px; /* 边框圆角 */\n"
"    \n"
"    image: url(:/resources/folder.png);\n"
"}")
        self.label_reg_logo.setText("")
        self.label_reg_logo.setObjectName("label_reg_logo")
        self.label_reg_png = QtWidgets.QLabel(self.page)
        self.label_reg_png.setGeometry(QtCore.QRect(130, 160, 81, 51))
        self.label_reg_png.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    font: 75 24pt \"Microsoft New Tai Lue\";\n"
"font-weight:bold;\n"
"}\n"
"")
        self.label_reg_png.setObjectName("label_reg_png")
        self.label_reg_pic = QtWidgets.QLabel(self.page)
        self.label_reg_pic.setGeometry(QtCore.QRect(70, 110, 171, 131))
        self.label_reg_pic.setText("")
        self.label_reg_pic.setScaledContents(True)
        self.label_reg_pic.setObjectName("label_reg_pic")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(80, 280, 54, 12))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 311, 41))
        self.label_5.setStyleSheet("QLabel{\n"
"color:rgb(233, 82, 63);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 56, 56))
        self.label_6.setStyleSheet("image: url(:/resources/idea.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(60, 270, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"    background-color: rgb(39, 41, 101);\n"
"    border-radius: 14px;\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 4px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 4px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 110, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_3.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 200, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_4.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(360, 270, 60, 60))
        self.label_7.setStyleSheet("image: url(:/resources/polar-bear.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_rec_bg = QtWidgets.QLabel(self.page_2)
        self.label_rec_bg.setGeometry(QtCore.QRect(50, 90, 210, 170))
        self.label_rec_bg.setStyleSheet("QLabel{\n"
"background-color: rgb(102, 114, 252);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"}")
        self.label_rec_bg.setText("")
        self.label_rec_bg.setObjectName("label_rec_bg")
        self.label_rec_logo = QtWidgets.QLabel(self.page_2)
        self.label_rec_logo.setGeometry(QtCore.QRect(80, 110, 40, 40))
        self.label_rec_logo.setStyleSheet("QLabel{\n"
"background-color: rgb(128, 129, 228);\n"
"border-radius: 12px; /* 边框圆角 */\n"
"    \n"
"    image: url(:/resources/folder.png);\n"
"}")
        self.label_rec_logo.setText("")
        self.label_rec_logo.setObjectName("label_rec_logo")
        self.label_rec_png = QtWidgets.QLabel(self.page_2)
        self.label_rec_png.setGeometry(QtCore.QRect(130, 160, 81, 51))
        self.label_rec_png.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    font: 75 24pt \"Microsoft New Tai Lue\";\n"
"font-weight:bold;\n"
"}\n"
"")
        self.label_rec_png.setObjectName("label_rec_png")
        self.label_rec_pic = QtWidgets.QLabel(self.page_2)
        self.label_rec_pic.setGeometry(QtCore.QRect(70, 110, 171, 131))
        self.label_rec_pic.setText("")
        self.label_rec_pic.setScaledContents(True)
        self.label_rec_pic.setObjectName("label_rec_pic")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(70, 280, 171, 51))
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(102, 114, 252);\n"
"    border-image: url(:/resources/label_white.png);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"border-radius: 10px; /* 边框圆角 */\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 56, 56))
        self.label_8.setStyleSheet("image: url(:/resources/miss.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(100, 20, 311, 41))
        self.label_9.setStyleSheet("QLabel{color: rgb(102, 114, 252);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 110, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_5.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 200, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_6.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(360, 270, 60, 60))
        self.label_10.setStyleSheet("image: url(:/resources/cat.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_v_bg_1 = QtWidgets.QLabel(self.page_3)
        self.label_v_bg_1.setGeometry(QtCore.QRect(30, 30, 170, 170))
        self.label_v_bg_1.setStyleSheet("QLabel{\n"
"background-color: rgb(233, 82, 63);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"}")
        self.label_v_bg_1.setText("")
        self.label_v_bg_1.setObjectName("label_v_bg_1")
        self.label_v_bg_2 = QtWidgets.QLabel(self.page_3)
        self.label_v_bg_2.setGeometry(QtCore.QRect(240, 30, 170, 170))
        self.label_v_bg_2.setStyleSheet("QLabel{\n"
"background-color: rgb(247, 183, 73);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"}")
        self.label_v_bg_2.setText("")
        self.label_v_bg_2.setObjectName("label_v_bg_2")
        self.label_v_logo_1 = QtWidgets.QLabel(self.page_3)
        self.label_v_logo_1.setGeometry(QtCore.QRect(50, 50, 40, 40))
        self.label_v_logo_1.setStyleSheet("QLabel{\n"
"background-color: rgb(254, 113, 106);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"    \n"
"image: url(:/resources/instagram.png);\n"
"}")
        self.label_v_logo_1.setText("")
        self.label_v_logo_1.setObjectName("label_v_logo_1")
        self.label_v_logo_2 = QtWidgets.QLabel(self.page_3)
        self.label_v_logo_2.setGeometry(QtCore.QRect(260, 50, 40, 40))
        self.label_v_logo_2.setStyleSheet("QLabel{\n"
"background-color: rgb(237, 206, 126);\n"
"border-radius: 20px; /* 边框圆角 */\n"
"    \n"
"    image: url(:/resources/instagram.png);\n"
"}")
        self.label_v_logo_2.setText("")
        self.label_v_logo_2.setObjectName("label_v_logo_2")
        self.label_v_png_1 = QtWidgets.QLabel(self.page_3)
        self.label_v_png_1.setGeometry(QtCore.QRect(50, 100, 141, 61))
        self.label_v_png_1.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"Microsoft New Tai Lue\";\n"
"font-weight:bold;\n"
"}\n"
"")
        self.label_v_png_1.setObjectName("label_v_png_1")
        self.label_v_png_2 = QtWidgets.QLabel(self.page_3)
        self.label_v_png_2.setGeometry(QtCore.QRect(250, 100, 161, 61))
        self.label_v_png_2.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"Microsoft New Tai Lue\";\n"
"font-weight:bold;\n"
"}\n"
"")
        self.label_v_png_2.setObjectName("label_v_png_2")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 131, 131))
        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(260, 50, 131, 131))
        self.label_11.setText("")
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 220, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_7.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 290, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_8.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(250, 240, 81, 51))
        self.label_12.setStyleSheet("QLabel{\n"
"color: rgb(247, 183, 73);\n"
"    border-image: url(:/resources/label_white.png);\n"
"font: 75 14pt \"Microsoft JhengHei\";\n"
"font-weight: bold;\n"
"border-radius: 8px; /* 边框圆角 */\n"
"}")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(360, 270, 60, 60))
        self.label_13.setStyleSheet("image: url(:/resources/panda.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_3)
        self.pushButton_min = QtWidgets.QPushButton(Form)
        self.pushButton_min.setGeometry(QtCore.QRect(620, 60, 22, 22))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"    background:#9D9D9D;\n"
"    color:white;\n"
"    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 11px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(194, 194, 194);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_close = QtWidgets.QPushButton(Form)
        self.pushButton_close.setGeometry(QtCore.QRect(670, 60, 22, 22))
        self.pushButton_close.setStyleSheet("QPushButton{\n"
"    background:#CE0000;\n"
"    color:white;\n"
"    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);\n"
"    font-size:16px;border-radius: 11px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#FF2D2D;\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Name.setText(_translate("Form", "LFace"))
        self.pushButton_register.setText(_translate("Form", "    Register"))
        self.pushButton_recognition.setText(_translate("Form", "    Recognize"))
        self.pushButton_verification.setText(_translate("Form", "    Verify"))
        self.label_reg_png.setText(_translate("Form", "PNG"))
        self.label_5.setText(_translate("Form", "Please register with your name ~"))
        self.lineEdit.setPlaceholderText(_translate("Form", "         your name"))
        self.pushButton_3.setText(_translate("Form", "Upload"))
        self.pushButton_4.setText(_translate("Form", "Register"))
        self.label_rec_png.setText(_translate("Form", "PNG"))
        self.label_3.setText(_translate("Form", "     Who are you?"))
        self.label_9.setText(_translate("Form", "Please recognize after register ~"))
        self.pushButton_5.setText(_translate("Form", "Upload"))
        self.pushButton_6.setText(_translate("Form", "Recognize"))
        self.label_v_png_1.setText(_translate("Form", "FIRST YOU"))
        self.label_v_png_2.setText(_translate("Form", "SECOND YOU"))
        self.pushButton_7.setText(_translate("Form", "Upload"))
        self.pushButton_8.setText(_translate("Form", "Verify"))
        self.label_12.setText(_translate("Form", "   Yes ?"))
import new_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
